### PR TITLE
Migrate Refresh

### PR DESCRIPTION
**Pull request by i74ifa**
Just add Migrate Refresh
We need a way to refresh migrations files and option a specific file with ```--path``` to refresh it

### CODE REVIEW

**Comment by stancl** [comment]
1. Why isn't `migrate:fresh` enough for your use case?
2. What's the point of the `--path` argument?

**Comment by i74ifa** [comment]
Migrate fresh will fresh all the files 

But in my case, I want to refresh only one file
I don't know why `tenants:rollback` not accurate when i use `--path`

**Comment by stancl** [comment]
Write that more clearly and in more detail.

**Comment by i74ifa** [comment]
I now have` create_users_table.php` file
  I modified or added some columns
When I want to rollback using a command
`php artisan tenants:rollback --path=database/migration/tenants/create_users_table.php`
It recognizes the file but rollback does not work
This is my problem with rollback

But migrate:refresh

According to Laravel
> The `migrate:refresh `command will roll back all of your migrations and then execute the migrate command. This command effectively re-creates your entire database.


It is working properly

**Comment by stancl** [comment]
I don't think we'll want to include this.

You should make your development environment stable enough so that you can run `migrate:fresh --seed` and be able to test the app, without having to roll back and re-run individual migrations.

**Pull request closed without merging**
