### PR TITLE
Add schema dump command

### PR DESCRIPTION
**Pull request by viicslen**
Add schema dump command for the tenant context.

It accepts a tenant identifier as `tenant` option. If the option is not provided, it prompt the user for it or if there is no input, it will try to get the first tenant from the database.

Schema file will be created inside of the `database/schema` folder with the default name of `tenant-schema.sql`

### CODE REVIEW

**Comment by viicslen** [comment]
This is just some initial concept, I will be happy to write tests and organize it a bit more if the PR gets approval

**Comment by stancl** [comment]
Can you look into the failing check?

> it prompt the user for it or if there is no input, it will try to get the first tenant from the database.

And it uses just the tenant's *schema*, right? Not his data. Going for the first one is probably a safe default in that case. Tenancy makes this feature a bit more complex since different tenants can be at a different "stages" of migrations, but the first one should always be up to date.

**Comment by viicslen** [comment]
> Can you look into the failing check?

Sure, I will look into it once I get home today

> And it uses just the tenant's schema, right?

Yes, just the schema along with the migrations table data so that it doens't try to run previous migrations once the schema is restored. The logic in the command is mainly for getting the tenant and initializing it. It uses Laravel's default behavior for creating the schema dump.

In theory since the migrate command uses Laravel's logic for migrating the database it should initialize the tenant's database with the tenant's schema and then run remaining migrations not included in the schema dump.

**Comment by viicslen** [comment]
Added test for dumping and loading tenant schema and added conditional loading for Laravel 8 and up since the schema functionality was added in that version.

**Comment by viicslen** [comment]
Sorry, I had removed the rollback command from the service provider by mistake when I tried to add conditional registering of the dump command based on larevel versions

**Comment by stancl** [comment]
The imported `DumpCommand` doesn't seem to exist in Laravel 6

**Comment by stancl** [comment]
I think it was added in Laravel 8 actually, so that'd make sense.

In that case, it'd probably be better to PR this to the master branch (which will be used for v4).

**Comment by viicslen** [comment]
Yeah, I was afraid that might be the best solution. I did register the command conditionally if the installed laravel version is 8 and up but PHPUnit is still going to complain about it.

Alright, I will change the target to the master branch instead and remove the conditional registering code

**Comment by stancl** [comment]
> I did register the command conditionally if the installed laravel version is 8 and up but PHPUnit is still going to complain about it.

Yeah, I wasn't sure what the behavior would be — if it'd only matter with actual usage of the class, or if the existence itself would break autoloading — but apparently it's the latter. So sending this to master would be best.

I'm thinking that if there are more features like this, we could have a semi-stable branch that requires Laravel 8/9, but is otherwise backwards compatible with v3. Like a step between v3 and v4. It wouldn't be guaranteed to be bug-free, but it should be stable enough for development, or staging/production if the version gets properly locked.

**Comment by viicslen** [comment]
Closed in favor of #807.

PS: Sorry for messed up commit history on this one. This is actually my second PR ever to any GH project and I still haven't familiarized with the whole rebase option

**Comment by stancl** [comment]
No worries, I squash-merge PRs anyway so the PR will only add one commit to the codebase 👍🏻

**Pull request closed without merging**
