### PR TITLE
Check DB existsance  as config

### PR DESCRIPTION
**Pull request by oniz93**
I have a project with an high I/O (20/30 API requests per second) and using all the caches remains a query to the DB: the one  that check DB existence.
I would like to make optional that query since I'm the admin of the DB and I know when a DB exists or not.

I hope that it's a good feature :)

### CODE REVIEW

**Comment by oniz93** [comment]
I don't know why codeconv says that the coverage is less. I just added a bunch of "if"...

**Comment by stancl** [comment]
Where is the method called? DB existence should only be checked on tenant *creation* in production, not on requests.

https://github.com/stancl/tenancy/blob/411d486282517956ae32976cabe2cda07ad887ab/src/Bootstrappers/DatabaseTenancyBootstrapper.php#L27-L32

**Comment by oniz93** [comment]
In my case I use PostgreSQLSchemaManager and it's checked at each bootstrap of the application, not only on tenant creation.
I modified all the DB Managers because I thought that the behaviour it's always the same.
Let me know if this is the behaviour only for PostgreSQLSchemaManager and I'll change only there

**Comment by stancl** [comment]
See the code I sent. Do you have the correct environment configured in production?

**Comment by oniz93** [comment]
You are right. The problem was my APP_ENV.
Thank you so much!
I close the PR

**Pull request closed without merging**
