### PR TITLE
Fix typo in TenantRouteServiceProvider

### PR DESCRIPTION
**Pull request by franzyke**
config `tenant_route_namespace` was used instead  of
`tenancy.tenant_route_namespace`

### CODE REVIEW

**Comment by stancl** [comment]
It should be `tenancy.tenant_route_namespace`, because the `tenant_route_namespace` config key is located in the `tenancy` config file.

Are you having some issues with the controller namespace in your tenant routes?

**Comment by franzyke** [comment]
It was `tenant_route_namespace` in the TenantRouteServiceProvider.php file. I changed that to `tenancy.tenant_route_namespace` and submitted this pull request

**Comment by franzyke** [comment]
It was `tenant_route_namespace` in the TenantRouteServiceProvider.php file. I changed that to `tenancy.tenant_route_namespace` and submitted this pull request

**Comment by stancl** [comment]
Oh right, sorry, misread the diff.

Thanks!

**Pull request merged**
