### PR TITLE
Fix eloquent relational query

### PR DESCRIPTION
**Pull request by ashraful19**
Fixing error "Call to a member function where() on array " error

### CODE REVIEW

**Comment by stancl** [comment]
Could you share what needs to happen for this bug to occur?

**Comment by ashraful19** [comment]
Hi @stancl 
When a `InitializeTenancyByDomain` or `InitializeTenancyBySubdomain` or `InitializeTenancyByDomainOrSubdomain` middleware is used, and the tenant is found, this error is shown as the resolver cant set the current domain, because `$tenant->domains` is returning an `array` but it should return a `Illuminate\Database\Eloquent\Relations\HasMany` object to chain further `where()` method

**Comment by stancl** [comment]
I don't think this fix should be needed, there weren't any issues with this in the past. And here it'd be unnecessarily bypassing the loaded relation data.

Are you using some custom setup? I'm not sure why this would be happening to you but not others

**Comment by ashraful19** [comment]
It was strange to me too that why this didnt happened to others. I didnt have any custom setup, only installed the package in my existing application. 
the problem is `$tenant->domains` isnt returning a relation/collection but a plain array, and thus the further chained `where()` gives error. 
At the moment i ended up making a custom middleware and custom resolver. 
I will check more in deep why i am getting a plain array with `$tenant->domains` and not anyone else.

Will update you.

**Pull request closed without merging**
