### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
Following your request in the tweet:
https://twitter.com/samuelstancl/status/1179473338667802624

Here it is your brand new logo. Hope you like it!

image

### CODE REVIEW

**Comment by stancl** [comment]
Hi @Caneco, thanks a lot!

Looks very good, I really like the drawing. 

Could I ask for an svg so that I can tweak the colors a bit to make them more aligned with the [landing page's](https://tenancy.samuelstancl.me) colors?

Thanks again!

**Comment by caneco** [comment]
@stancl sure! What about this set of colours?
image

Sorry to not going this way at the first place, but I'm painting mostly everything related to Laravel using that orange palette.

**Comment by caneco** [comment]
Note: maybe for the landing page it would be nicer to have a version in gradients of white and light gray.

**Comment by caneco** [comment]
Just updated the logo… hope it fits 😄

**Comment by stancl** [comment]
> What about this set of colours?

Looks nice! May I ask for a version that goes "one shade lighter"? I liked how the orange version was very light at some parts & also the "shape" of the gradient in the orange version.

> maybe for the landing page it would be nicer to have a version in gradients of white and light gray.

So that it could be placed in, say, a navbar on the indigo background? Makes sense.

**Comment by caneco** [comment]
> May I ask for a version that goes "one shade lighter"?
Here you have it… any good?
image


And on top of the indigo hero
image

**Comment by stancl** [comment]
Looks sweet! Let's go with that.

As for the light version, I was thinking about the landing page design and I couldn't decide how I'd style the navbar. Could I get the housetacpus in svg? (Or if by any chance you used Figma, I'd be fine with that too.)

**Comment by caneco** [comment]
Just updated the PR with a lighter logo
image


> Could I get the housetacpus in svg?
Regarding the SVGs, I'm asking for everyone to ping me on November (according to the [CoC](https://www.notion.so/Do-you-need-a-logo-14b46a005e184aaca3481f722d765a90)). Possible?

**Comment by stancl** [comment]
> I'm asking for everyone to ping me on November

Sure thing.

Thanks a lot again!

**Comment by stancl** [comment]
Hi @caneco, could I ask for the svg? I want to add a navbar to the website so I'd like to play with the colors a bit.

Thanks!

**Pull request merged**
