### PR TITLE
SqlServer Support

### PR DESCRIPTION
**Pull request by AmrIbrahem99**
Added SqlSrv support (including permission control)

### CODE REVIEW

**Comment by stancl** [comment]
I think this was added for v4 in #715

**Comment by stancl** [comment]
Hmm maybe we don't have the permission controlled version?

**Comment by AmrIbrahem99** [comment]
yes ! I think so,  there is no SchemaManager too 
i mean i didnt work on that but i think its applicable

**Comment by stancl** [comment]
What do you mean by "no SchemaManager"?

**Comment by AmrIbrahem99** [comment]
like pg SchemaManager

**Comment by AmrIbrahem99** [comment]
did you take a look on permission controller  yet?

**Comment by AmrIbrahem99** [comment]
I think this pull request been dead for a while XD

> Hmm maybe we don't have the permission controlled version?

**Comment by stancl** [comment]
We have reimplemented something similar in the v4 repo. Only adding the permission controlled one now, though it's a bit different and tests are included.

Appreciate the contribution but will have to close this in favor of the other PR.

**Pull request closed without merging**
