### PR TITLE
[4.x] Set up phpstan

### LINKED ISSUE #910: [4.x] Set up phpstan

### PR DESCRIPTION
**Pull request by abrardev99**

### CODE REVIEW

**Comment by abrardev99** [comment]
Currently, We have 252 errors. 

image

I see a lot of them can be fixed by simply adding types. @stancl, should we use docblock or PHP built-in types?

**Comment by stancl** [comment]
I'll work on fixing those 👍🏻 We'll be using proper types wherever possible.

**Comment by stancl** [comment]
Can you add phpstan to the CI as well? It should be a separate check, similar to php-cs-fixer.

**Comment by stancl** [comment]
I'll merge this now to have phpstan in master. Please send a separate PR for the CI workflow 👍🏻 

Thanks!

**Pull request merged**
