### PR TITLE
[4.x] Add ScoutTenancyBootstrapper

### PR DESCRIPTION
**Pull request by lukinovec**
Related PR: https://github.com/stancl/tenancy-docs/pull/193

### CODE REVIEW

**Comment by stancl** [comment]
Great implementation, making a minor change and merging this straight away 👍🏻

**Comment by stancl** [comment]
Added a method to make customizing this easy — now people can extend the bootstrapper and just override that one method to customize how the prefixes are generated.

Can you test this code locally in your Scout repo to see if it works well? And update the docs PR.

**Comment by lukinovec** [comment]
> Can you test this code locally in your Scout repo to see if it works well? And update the docs PR.

Works fine 👍

**Comment by wilsenhc** [comment]
@lukinovec @stancl is this something that could be back-ported or used with Tenancy v3? Have you tried it out?

**Comment by stancl** [comment]
There's nothing v4-specific in the bootstrapper I think. But we won't be adding it to v3

**Pull request merged**
