### PR TITLE
Support for soft delete events

### PR DESCRIPTION
**Pull request by savchukoleksii**
@stancl

### CODE REVIEW

**Comment by hyquality** [comment]
@stancl Can you review PR, please?
This pull request add tenant soft delete events system support.

**Comment by savchukoleksii** [comment]
@stancl Can you review PR please?
This PR add ability to support soft/force deleting tenants.

**Comment by stancl** [comment]
I'm not sure if this is needed. Generally people use custom mechanisms for disabling tenants, and soft deletes aren't IMO a good idea here.

That said, nothing is stopping the developer from adding soft deletes to the tenant model in their application.

**Comment by savchukoleksii** [comment]
@stancl
My idea was to create build-in solution for this.

**Comment by stancl** [comment]
I don't think it'd make much sense to be honest. It's very easy to add in the app, and chances are that you'd be using a more custom setup than this. I also don't want to encourage using soft deletes with tenants, as people should use custom logic that will handle everything they need.

**Pull request closed without merging**
