### PR TITLE
Refactor checking host is subdomain

### PR DESCRIPTION
**Pull request by suleymanozev**
When use endsWith throw 500 server error with is not subdomain host is not subdomain.

I check subdomain really exists.

### CODE REVIEW

**Comment by stancl** [comment]
The PR description should explain why this change is beneficial to the package.

**Comment by suleymanozev** [comment]
Because, wrong way checking host is a subdomain.

**Comment by suleymanozev** [comment]
Please review code. My english is bad.

**Comment by stancl** [comment]
The code change looks like it goes from checking that the **hostname ends with a central domain** to simply checking that **the central domain is included in the hostname anywhere**?

I don't understand why we would make this change.

**Pull request closed without merging**
