### PR TITLE
[4.x] [WIP] Add phpstan to CI

### PR DESCRIPTION
**Pull request by abrardev99**
Continues of PR https://github.com/archtechx/tenancy/pull/926

### CODE REVIEW

**Comment by stancl** [comment]
FYI you can create branches in this repo for simple PRs. It would work better because then I could check out this branch and easily make changes in it.

So now we'll keep this open until I tell you to merge `master` into your branch after I resolve the issues there.

**Comment by abrardev99** [comment]
> FYI you can create branches in this repo for simple PRs. It would work better because then I could check out this branch and easily make changes in it.

Sure. BTW, I think you can checkout out specific PR too.

**Comment by stancl** [comment]
That's with the GitHub CLI, right?

**Comment by abrardev99** [comment]
> That's with the GitHub CLI, right?

I think GitHub CLI can do that too, but I often use GitHub Desktop.

**Comment by stancl** [comment]
I see, I just use CLI `git`

**Comment by chrillep** [comment]
> I see, I just use CLI `git`

not to derail the PR. but you can install git add-ons to checkout PR's then you don't have to leave `git`.

in git-extras you get `git pr`

https://github.com/tj/git-extras

more fun stuff on -> https://github.com/stevemao/awesome-git-addons

**Comment by stancl** [comment]
I resolved many issues in `master` and all issues related to resource syncing in #915, so after that is merged there will be only 3 issues left:

```
 ------ ------------------------------------------------------- 
  Line   Middleware/InitializeTenancyByPath.php                 
 ------ ------------------------------------------------------- 
  55     Unreachable statement - code above always terminates.  
 ------ ------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   Tenancy.php                                                                                                                                                            
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  46     Cannot call method getTenantKey() on (Illuminate\Database\Eloquent\Model&Stancl\Tenancy\Contracts\Tenant)|null.                                                        
  55     Property Stancl\Tenancy\Tenancy::$tenant ((Illuminate\Database\Eloquent\Model&Stancl\Tenancy\Contracts\Tenant)|null) does not accept Stancl\Tenancy\Contracts\Tenant.  
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 3 errors                                                                                                 
```

These are a bit more difficult so I'll try to refactor the code to fix them.

**Comment by stancl** [comment]
All phpstan issues are resolved 🚀 Thanks for working on the CI workflow!

**Pull request merged**
