### PR TITLE
Pull 3.x changes into master

### PR DESCRIPTION
**Pull request by stancl**

### CODE REVIEW

**Comment by stancl** [comment]
@abrardev99 Could you resolve these conflicts?
- In `ci.yml`, just go with the `master` version
- In `CONTRIBUTING.md`, also go with the `master` version
- In test files, convert the changes to pest syntax

I wanted to push the first two myself, but GH only lets you commit conflict resolution for all files at once.

**Comment by abrardev99** [comment]
@stancl All conflicts are resolved.

**Comment by stancl** [comment]
Hmm seems like this PR caused issues, specifically this commit: https://github.com/archtechx/tenancy/commit/158088faae719410d3ccfc3ac54223212b0231c4

We now have `master` changes in `3.x` even though this PR got merged into `master`

**Comment by stancl** [comment]
Ah, it doesn't matter that this PR was targeting `master` because it was coming directly from `3.x`, so @abrardev99's commit during conflict resolution got added to `3.x`, merging all the changes we had in `master` into `3.x`

**Comment by stancl** [comment]
Fixed this by resetting the branch to a point before https://github.com/archtechx/tenancy/commit/158088faae719410d3ccfc3ac54223212b0231c4 and then cherry picking the two new commits that were added after this PR. Force pushed `3.x` to that state.

**Pull request merged**
